image: ubuntu:20.04

stages:
  - deploy

before_script:
  - apt-get update
  - apt-get install -y python3-pip curl
  - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
  - apt-get install -y nodejs
  - node -v
  - npm -v
  - npm install -g serverless@3
  - pip3 install awscli

deploy_dev:
  stage: deploy
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_DEV
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default
    - aws configure set region $AWS_DEFAULT_REGION_DEV --profile default
    - aws sts get-caller-identity
    #- serverless deploy --stage dev --region $AWS_DEFAULT_REGION_DEV
    #- serverless remove --stage dev --region $AWS_DEFAULT_REGION_DEV
  environment:
    name: dev
  only:
    - dev

deploy_uat:
  stage: deploy
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_UAT
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default
    - aws configure set region $AWS_DEFAULT_REGION_UAT --profile default
    - aws sts get-caller-identity
    #- serverless deploy --stage uat
    #- serverless remove --stage uat
  environment:
    name: uat
  only:
    - uat

deploy_prod:
  stage: deploy
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_PROD
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default
    - aws configure set region $AWS_DEFAULT_REGION_PROD --profile default
    - aws sts get-caller-identity
    - serverless remove --stage prod
    #- serverless deploy --stage prod
    
  environment:
    name: master
  only:
    - master